#version 430

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(binding = 2, offset = 4) uniform atomic_uint at1;

uniform int mipLevel = 0;
uniform sampler3D grid;

layout(std430, binding = 1) buffer PosBuffer {
	vec4 position[];
};

void main()
{
	uint res;
	ivec3 pos = ivec3(gl_GlobalInvocationID);
	vec4 srcColor0 = texelFetch(grid, pos, mipLevel);
	
	if (srcColor0.a != 0) {
		res = atomicCounterIncrement(at1);
		position[res] = vec4(vec3(pos),1.0);
	}
}
