#version 430

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(binding = 1, rgba8) uniform coherent volatile image3D imageUnit;


void main()
{
	uint res;
	ivec3 pos = ivec3(gl_GlobalInvocationID);
	vec4 srcColor0 = imageLoad(imageUnit, pos);
	
	if (length(srcColor0) != 0) {
//		if (srcColor0.r == 1.0)
//			srcColor0 = vec4(0,0,0,0);
		imageStore(imageUnit, pos, vec4(srcColor0.xyz ,1.0));
	}
}
